version: '3.8'

services:
  mongo:
    image: mongo:6
    container_name: week12-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass1234
      MONGO_INITDB_DATABASE: week12
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
